### ISSUE TITLE
请问关于算法输入是RGB格式还是BGR格式？

### ISSUE THREAD

**Issue by zhuMingXu** [LCH1238/bevdet-tensorrt-cpp#12]
python torch版本，在dataload里面，将数据转换为了RGB格式。

但是在该版本的C++实现里面，首先经过decode_jpeg 得到了RGB_HWC格式，然后调用了函数convert_RGBHWC_to_BGRCHW转换为BGRCHW格式？？？所以最终输入的是BGR格式，这是bug吗？

**Comment by zhuMingXu** [comment]
![企业微信截图_16916552891668](https://github.com/LCH1238/bevdet-tensorrt-cpp/assets/36021335/7f777c00-8f73-4edc-a98c-de2deb6b0bd8)

**Comment by zbl-96** [comment]
在bevdet库里是使用了pil open为rgb 然后又使用了mmlabNormalize转换通道到bgr，所以这里是bgr？ 如果我的理解错误请立即指正我   https://github.com/HuangJunJie2017/BEVDet/issues/274#issue-1808990733
