### ISSUE TITLE
请问应该如何得到mAP？

### ISSUE THREAD

**Issue by TGpastor** [LCH1238/bevdet-tensorrt-cpp#15]
感谢您开源这个项目，我在Xavier上成功得到了txt格式的egobbox，但是不清楚如何使用这些txt生成mAP，我注意到您在主页上列出了模型的mAP，请问您是否方便开源一下用于检测mAP的代码，或是大概介绍一下使用mmdet相关工具进行后处理的流程？

**Comment by LCH1238** [comment]
稍后我会发布这部分的代码

**Comment by LCH1238** [comment]
可以使用这个脚本在nuScenes Val集上面测试。[code](https://github.com/LCH1238/BEVDet/blob/export/tools/export/test.py)

**Comment by TGpastor** [comment]
> 可以使用这个脚本在nuScenes Val集上面测试。[code](https://github.com/LCH1238/BEVDet/blob/export/tools/export/test.py)

非常感谢！
