### ISSUE TITLE
TypeError: tuple indices must be integers or slices, not tuple

### ISSUE THREAD

**Issue by warbrain** [LCH1238/bevdet-tensorrt-cpp#22]
Hello, @LCH1238, Thanks your work.

When i using your export branch, running **python tools/train.py configs/bevdet/bevdet-r50-4dlongterm-depth-cbgs.py**, get this error.  The official version is OK.  Do you have any option resolve it. Thanks.
![Screenshot from 2023-12-07 22-11-20](https://github.com/LCH1238/bevdet-tensorrt-cpp/assets/5722854/b86ef506-75bb-4b55-af2e-188e552da98c)

**Comment by warbrain** [comment]
environment:
python 3.7/3.8
pytorch 1.9
cuda 11.1
mmcv-full 1.5.3
mmdet 2.25.1 
mmsegmentation 0.25.0

**Comment by warbrain** [comment]
modify sth, now is OK.

**Comment by WangY69** [comment]
Please tell me which modifications have been made to solve this problem, as I have also encountered it...
