### ISSUE TITLE
export_onx_onnx.py导出的合一版本onnx，转换tensorrt后推理，只检测出了2个object，实际上应该是100个左右

### ISSUE THREAD

**Issue by vilon888** [LCH1238/bevdet-tensorrt-cpp#27]
你好， @LCH1238 ， 使用你合一版本的onnx，针对sample的例子，只检测出了2个obj, 实际应该是100左右， 请问这是哪里配置问题吗？
**具体命令及结果如下：**

./bevdemo  ../configure.yaml 

GPU has cuda devices: 1
----device id: 0 info----
  GPU : NVIDIA GeForce RTX 4090 
  Capbility: 8.9
  Global memory: 24209MB
  Const memory: 64KB
  Shared memory in a block: 48KB
  warp size: 32
  threads in a block: 1024
  block dim: (1024,1024,64)
  grid dim: (2147483647,65535,65535)

Successful load config : ../configure.yaml!
1.00 0.70 0.70 0.40 0.55 1.10 1.00 1.00 1.50 3.50
valid_feat_num: 356760 
unique_bev_num: 13360 
InitVewTransformer cost time : 12.0418 ms
Binding 0 (images): Input. 
Binding 1 (mean): Input. 
Binding 2 (std): Input. 
Binding 3 (cam_params): Input. 
Binding 4 (ranks_depth): Input. 
Binding 5 (ranks_feat): Input. 
Binding 6 (ranks_bev): Input. 
Binding 7 (interval_starts): Input. 
Binding 8 (interval_lengths): Input. 
Binding 9 (adj_feats): Input. 
Binding 10 (transforms): Input. 
Binding 11 (flag): Input. 
Binding 12 (curr_bevfeat): Output. 
Binding 13 (reg_0): Output. 
Binding 14 (height_0): Output. 
Binding 15 (dim_0): Output. 
Binding 16 (rot_0): Output. 
Binding 17 (vel_0): Output. 
Binding 18 (heatmap_0): Output. 
images : 6 3 900 400
mean : 3
std : 3
cam_params : 1 6 27
ranks_depth : 356760
ranks_feat : 356760
ranks_bev : 356760
interval_starts : 13360
interval_lengths : 13360
adj_feats : 1 8 80 128 128
transforms : 1 8 6
flag : 1 1
curr_bevfeat : 1 80 128 128
reg_0 : 1 2 128 128
height_0 : 1 1 128 128
dim_0 : 1 3 128 128
rot_0 : 1 2 128 128
vel_0 : 1 2 128 128
heatmap_0 : 1 10 128 128

img num binding : 19
-------------------0-------------------
**scenes_token : e7ef871f77f44331aefdebc24ec034b7, timestamp : 1533201470448696
TRT-Engine  : 45.86426 ms
Postprocess : 0.23169 ms
Inference   : 46.09595 ms
Detect 2 objects**

**Comment by lyxbyr** [comment]
@vilon888 你好，你那边能正常导出onnx是吗，你仓库是基于原作者的dev2.1分支还是这边的export分支，我这边都试了还是一样的问题，是环境的原因吗，环境应该是对的，总是报那个错

Thank you for this great work! I used the bevdet-export repo to convert 'bevdet-lt-d-ft-nearest.pth' or 'bevdet-r50-4dlongterm-depth-cbgs.pth' to onnx format, but got an error as follow:

"./BEVDet-export/mmdet3d/models/detectors/trt_model.py", line 67, in forward
x, mlp_bn, con_se, depth_se = self.img_view_transformer.depth_net(r, mlp_input)
ValueError: not enough values to unpack (expected 4, got 2)

**Comment by vilon888** [comment]
@lyxbyr 

我是基于export分支的，可以正常导出，没有遇到你这个问题； export 这个分支用的conda环境和原版BEVDET训练环境是一样的
我现在只是在推理的时候，结果不太对，还在看原因，只有和原作者推理一致，才能继续后面的修改。

**Comment by lyxbyr** [comment]
嗯，谢谢，我看了你是导的one吧，one也是可以正常导出的，但是结果不太对，执行export_onnx.py是报上面的错，加个vx？方便交流



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月30日 09:13 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [LCH1238/bevdet-tensorrt-cpp] export_onx_onnx.py导出的合一版本onnx，转换tensorrt后推理，只检测出了2个object，实际上应该是100个左右 (Issue #27) |

@vilon888 你好，你那边能正常导出onnx是吗，你仓库是基于原作者的dev2.1分支还是这边的export分支，我这边都试了还是一样的问题，是环境的原因吗，环境应该是对的，总是报那个错

Thank you for this great work! I used the bevdet-export repo to convert 'bevdet-lt-d-ft-nearest.pth' or 'bevdet-r50-4dlongterm-depth-cbgs.pth' to onnx format, but got an error as follow:

"./BEVDet-export/mmdet3d/models/detectors/trt_model.py", line 67, in forward x, mlp_bn, con_se, depth_se = self.img_view_transformer.depth_net(r, mlp_input) ValueError: not enough values to unpack (expected 4, got 2)

我是基于export分支的，可以正常导出，没有遇到你这个问题；
我现在只是在推理的时候，结果不太对，还在看原因，只有和原作者推理一致，我才能继续后面的修改。

**Comment by lyxbyr** [comment]
export_onx_onnx导出的模型我这边验证了结果是对的，就那个导不出报错。。。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月30日 09:13 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [LCH1238/bevdet-tensorrt-cpp] export_onx_onnx.py导出的合一版本onnx，转换tensorrt后推理，只检测出了2个object，实际上应该是100个左右 (Issue #27) |

@vilon888 你好，你那边能正常导出onnx是吗，你仓库是基于原作者的dev2.1分支还是这边的export分支，我这边都试了还是一样的问题，是环境的原因吗，环境应该是对的，总是报那个错

Thank you for this great work! I used the bevdet-export repo to convert 'bevdet-lt-d-ft-nearest.pth' or 'bevdet-r50-4dlongterm-depth-cbgs.pth' to onnx format, but got an error as follow:

"./BEVDet-export/mmdet3d/models/detectors/trt_model.py", line 67, in forward x, mlp_bn, con_se, depth_se = self.img_view_transformer.depth_net(r, mlp_input) ValueError: not enough values to unpack (expected 4, got 2)

我是基于export分支的，可以正常导出，没有遇到你这个问题；
我现在只是在推理的时候，结果不太对，还在看原因，只有和原作者推理一致，我才能继续后面的修改。

**Comment by vilon888** [comment]
> 嗯，谢谢，我看了你是导的one吧，one也是可以正常导出的，但是结果不太对，执行export_onnx.py是报上面的错，加个vx？方便交流
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年04月30日 09:13 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [LCH1238/bevdet-tensorrt-cpp] export_onx_onnx.py导出的合一版本onnx，转换tensorrt后推理，只检测出了2个object，实际上应该是100个左右 (Issue #27) | @vilon888 你好，你那边能正常导出onnx是吗，你仓库是基于原作者的dev2.1分支还是这边的export分支，我这边都试了还是一样的问题，是环境的原因吗，环境应该是对的，总是报那个错 Thank you for this great work! I used the bevdet-export repo to convert 'bevdet-lt-d-ft-nearest.pth' or 'bevdet-r50-4dlongterm-depth-cbgs.pth' to onnx format, but got an error as follow: "./BEVDet-export/mmdet3d/models/detectors/trt_model.py", line 67, in forward x, mlp_bn, con_se, depth_se = self.img_view_transformer.depth_net(r, mlp_input) ValueError: not enough values to unpack (expected 4, got 2) 我是基于export分支的，可以正常导出，没有遇到你这个问题； 我现在只是在推理的时候，结果不太对，还在看原因，只有和原作者推理一致，我才能继续后面的修改。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

我的微信是vilon888,你的是多少，我也可以添加你

**Comment by vilon888** [comment]
> export_onx_onnx导出的模型我这边验证了结果是对的，就那个导不出报错。。。
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年04月30日 09:13 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [LCH1238/bevdet-tensorrt-cpp] export_onx_onnx.py导出的合一版本onnx，转换tensorrt后推理，只检测出了2个object，实际上应该是100个左右 (Issue #27) | @vilon888 你好，你那边能正常导出onnx是吗，你仓库是基于原作者的dev2.1分支还是这边的export分支，我这边都试了还是一样的问题，是环境的原因吗，环境应该是对的，总是报那个错 Thank you for this great work! I used the bevdet-export repo to convert 'bevdet-lt-d-ft-nearest.pth' or 'bevdet-r50-4dlongterm-depth-cbgs.pth' to onnx format, but got an error as follow: "./BEVDet-export/mmdet3d/models/detectors/trt_model.py", line 67, in forward x, mlp_bn, con_se, depth_se = self.img_view_transformer.depth_net(r, mlp_input) ValueError: not enough values to unpack (expected 4, got 2) 我是基于export分支的，可以正常导出，没有遇到你这个问题； 我现在只是在推理的时候，结果不太对，还在看原因，只有和原作者推理一致，我才能继续后面的修改。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>
@lyxbyr 
export one导出成功，且验证通过，是用 @LCH1238 提供的模型 bevdet-lt-d-ft-nearest.pth，对吧？

我导出的参数是：
configs/bevdet/bevdet-r50-4dlongterm-depth-cbgs.py
models/bevdet-lt-d-ft-nearest.pth
--postfix=_lt_d

我用这个模型导出onnx后， 检测到了110个obj， 应该还是差点。
Successful load config : ../configure.yaml!
1.00 0.70 0.70 0.40 0.55 1.10 1.00 1.00 1.50 3.50
valid_feat_num: 356760 
unique_bev_num: 13360 
InitVewTransformer cost time : 12.9165 ms
Binding 0 (images): Input. 
Binding 1 (mean): Input. 
Binding 2 (std): Input. 
Binding 3 (cam_params): Input. 
Binding 4 (ranks_depth): Input. 
Binding 5 (ranks_feat): Input. 
Binding 6 (ranks_bev): Input. 
Binding 7 (interval_starts): Input. 
Binding 8 (interval_lengths): Input. 
Binding 9 (adj_feats): Input. 
Binding 10 (transforms): Input. 
Binding 11 (flag): Input. 
Binding 12 (curr_bevfeat): Output. 
Binding 13 (reg_0): Output. 
Binding 14 (height_0): Output. 
Binding 15 (dim_0): Output. 
Binding 16 (rot_0): Output. 
Binding 17 (vel_0): Output. 
Binding 18 (heatmap_0): Output. 
images : 6 3 900 400
mean : 3
std : 3
cam_params : 1 6 27
ranks_depth : 356760
ranks_feat : 356760
ranks_bev : 356760
interval_starts : 13360
interval_lengths : 13360
adj_feats : 1 8 80 128 128
transforms : 1 8 6
flag : 1 1
curr_bevfeat : 1 80 128 128
reg_0 : 1 2 128 128
height_0 : 1 1 128 128
dim_0 : 1 3 128 128
rot_0 : 1 2 128 128
vel_0 : 1 2 128 128
heatmap_0 : 1 10 128 128

img num binding : 19
-------------------0-------------------
scenes_token : e7ef871f77f44331aefdebc24ec034b7, timestamp : 1533201470448696
TRT-Engine  : 47.53143 ms
Postprocess : 0.48543 ms
Inference   : 48.01686 ms
Detect 110 objects

**Comment by vilon888** [comment]
use bevdet-lt-d-ft-nearest.pth model
