### ISSUE TITLE
自定义数据集使用单阶段模型进行推理时，如何完成从pth到onnx模型的转换

### ISSUE THREAD

**Issue by cyn-liu** [LCH1238/bevdet-tensorrt-cpp#28]
@LCH1238 非常感谢你的分享。

1. 使用如下仓库，即可使用NuScenes数据集训练模型。
https://github.com/LCH1238/BEVDet/tree/export

2. 直接用上述仓库下的`tools/export/export_onx_onnx.py`脚本，即可完成pth转onnx模型的操作。

3. 使用下面这个仓库，即可完成onnx模型转engine和engine的推理操作。
https://github.com/LCH1238/bevdet-tensorrt-cpp/tree/one

如上我都可以成功复现。

但是，我换了自己的数据集，修改配置中的数据参数后，进行模型训练，模型可以正常收敛。
我的数据集与NuScenes的区别仅仅只是原始图像的尺寸不同，`src_size=(1080, 1440)`。
如果我想转onnx，我需要如何修改`img_input`这个参数？？？
https://github.com/LCH1238/BEVDet/blob/d92b78471bb8b46072c96350848d6f32fb53b55e/tools/export/export_onx_onnx.py#L111

为什么这个单阶段模型的输入不直接设置为`input_size=(256,704)`呢？而是设置为`(900, 400)`。

**Comment by maoweinasa** [comment]
你自己场景数据跑起来了吗

> @LCH1238 非常感谢你的分享。
> 
> 1. 使用如下仓库，即可使用NuScenes数据集训练模型。
>    https://github.com/LCH1238/BEVDet/tree/export
> 2. 直接用上述仓库下的`tools/export/export_onx_onnx.py`脚本，即可完成pth转onnx模型的操作。
> 3. 使用下面这个仓库，即可完成onnx模型转engine和engine的推理操作。
>    https://github.com/LCH1238/bevdet-tensorrt-cpp/tree/one
> 
> 如上我都可以成功复现。
> 
> 但是，我换了自己的数据集，修改配置中的数据参数后，进行模型训练，模型可以正常收敛。 我的数据集与NuScenes的区别仅仅只是原始图像的尺寸不同，`src_size=(1080, 1440)`。 如果我想转onnx，我需要如何修改`img_input`这个参数？？？ https://github.com/LCH1238/BEVDet/blob/d92b78471bb8b46072c96350848d6f32fb53b55e/tools/export/export_onx_onnx.py#L111
> 
> 为什么这个单阶段模型的输入不直接设置为`input_size=(256,704)`呢？而是设置为`(900, 400)`。

你自己场景数据后来跑起来了吗？

**Comment by cyn-liu** [comment]
@maoweinasa  我的数据集可以跑起来，而且看起来应该是成功推理的，只是我的数据集比较小，训练出来的模型效果不好。
使用一阶段模型推理时，在pth转onnx模型时，作者的模型结构你可以看一下，有一点很关键，就是在输入端加了一个[预处理模块](https://github.com/LCH1238/BEVDet/blob/d92b78471bb8b46072c96350848d6f32fb53b55e/mmdet3d/models/detectors/trt_model.py#L276)，这个预处理模块有一个[计算公式](https://github.com/LCH1238/BEVDet/blob/d92b78471bb8b46072c96350848d6f32fb53b55e/mmdet3d/ops/bevdet_ops/onnx_ops.py#L97)，为了保证你的输出尺寸是[256,704]，所有要根据自己数据集的尺寸设置这几个参数`resize_ratio`、`crop_h`、`crop_w`

**Comment by maoweinasa** [comment]
> @maoweinasa 我的数据集可以跑起来，而且看起来应该是成功推理的，只是我的数据集比较小，训练出来的模型效果不好。 使用一阶段模型推理时，在pth转onnx模型时，作者的模型结构你可以看一下，有一点很关键，就是在输入端加了一个[预处理模块](https://github.com/LCH1238/BEVDet/blob/d92b78471bb8b46072c96350848d6f32fb53b55e/mmdet3d/models/detectors/trt_model.py#L276)，这个预处理模块有一个[计算公式](https://github.com/LCH1238/BEVDet/blob/d92b78471bb8b46072c96350848d6f32fb53b55e/mmdet3d/ops/bevdet_ops/onnx_ops.py#L97)，为了保证你的输出尺寸是[256,704]，所有要根据自己数据集的尺寸设置这几个参数`resize_ratio`、`crop_h`、`crop_w`

能加个联系方式不？微信：NASA1228

**Comment by persuelx** [comment]
@cyn-liu 你好我问一下，作者的process 模块在onnx模型中具体体现在哪里啊？
