### ISSUE TITLE
关于pth模型转onnx模型的问题

### ISSUE THREAD

**Issue by Yueh0** [LCH1238/bevdet-tensorrt-cpp#4]
你好，感谢开源代码。我在使用BEVDet提供的[BEVDet-R50-4DLongterm-Depth-CBGS](https://pan.baidu.com/s/1237QyV18zvRJ1pU3YzRItw?pwd=npe1)模型转onnx模型。参考BEVDet中mmdet3d/models/necks/view_transformer.py中get_mlp_input函数，不知道如何将rot、trans和bda如何关联起来。
![Screenshot from 2023-07-19 16-20-01](https://github.com/LCH1238/bevdet-tensorrt-cpp/assets/18463342/16598e36-6304-4e52-8ee8-1ee537b5e593)![Screenshot from 2023-07-19 16-42-17](https://github.com/LCH1238/bevdet-tensorrt-cpp/assets/18463342/e3270c41-44a4-4777-ab35-edea37da693a)
上图是我转换的img_stage的部分输入，跟你的比有明显差别。同时，我也转换了bev_stage，与你的比对输入输出和网络结构看起来是正常的。img_stage和bev_stage onnx模型可以转换为trt模型：

1. 使用你提供的环视图片推理，只能得到2个目标。
2. 使用你的img_stage模型，我自己转换的bev_stage模型只能得到20个目标。与你提供的模型得到100个目标相差甚远，感觉两个阶段转换的都有问题。

现在有两个问题，

1. img_stage中输入部分如何将rot、trans和bda如何关联起来？
2. bev_stage中转换有什么需要注意的问题？

希望提供一些指导，谢谢！

**Comment by LCH1238** [comment]
> 你好，感谢开源代码。我在使用BEVDet提供的[BEVDet-R50-4DLongterm-Depth-CBGS](https://pan.baidu.com/s/1237QyV18zvRJ1pU3YzRItw?pwd=npe1)模型。参考BEVDet中mmdet3d/models/necks/view_transformer.py中get_mlp_input函数，不知道如何将rot、trans和bda如何关联起来。 ![Screenshot from 2023-07-19 16-20-01](https://user-images.githubusercontent.com/18463342/254518865-16598e36-6304-4e52-8ee8-1ee537b5e593.png)![Screenshot from 2023-07-19 16-42-17](https://user-images.githubusercontent.com/18463342/254518940-e3270c41-44a4-4777-ab35-edea37da693a.png) 上图是我转换的img_stage的部分输入，跟你的比有明显差别。同时，我也转换了bev_stage，与你的比对输入输出和网络结构看起来是正常的。img_stage和bev_stage onnx模型可以转换为trt模型：
> 
> 1. 使用你提供的环视图片推理，只能得到2个目标。
> 2. 使用你的img_stage模型，我自己转换的bev_stage模型只能得到20个目标。与你提供的模型得到100个目标相差甚远，感觉两个阶段转换的都有问题。
> 
> 现在有两个问题，
> 
> 1. img_stage中输入部分如何将rot、trans和bda如何关联起来？
> 2. bev_stage中转换有什么需要注意的问题？
> 
> 希望提供一些指导，谢谢！

后续我将提供转换onnx模型的源码！

**Comment by LCH1238** [comment]
> 好的，感谢！

两天内

**Comment by LCH1238** [comment]
> 好的，感谢！

https://github.com/LCH1238/BEVDet

**Comment by Yueh0** [comment]
> > 好的，感谢！
> 
> https://github.com/LCH1238/BEVDet

收到，谢谢！我使用你给的pth模型，转换为onnx模型，最后进行推理没有问题。但是使用BEVDet官方给的[BEVDet-R50-4DLongterm-Depth-CBGS](https://pan.baidu.com/s/1237QyV18zvRJ1pU3YzRItw?pwd=npe1)模型，转成onnx模型，再推理结果不正确。想问一下重新训练模型，有哪写要注意的？

**Comment by LCH1238** [comment]
> 

我把BEV encoder的preprocess模块去除了，在readme里面有写。你可以参考https://github.com/LCH1238/BEVDet这个仓库里面bevdet的config。
