### ISSUE TITLE
Questions about abtain bev_feat_prev

### ISSUE THREAD

**Issue by cyn-liu** [LCH1238/bevdet-tensorrt-cpp#7]
Hello @LCH1238 , thank you for the open source code.

I have some questions, or maybe I misunderstood the code, welcome to correct.

For `BEVDet-r50-longterm-depth` model, before `bev_stage`, need to concatenate multiple frames `bev_feat_prev` and align them, however, I find `bev_feat_prev` in the code is not actual, but the same `bev_feat_curr` has been concatenated `num_adj` times.[code](https://github.com/LCH1238/bevdet-tensorrt-cpp/blob/134550610479ca62cc323b1b4a09a125e31c1599/src/bevdet.cpp#L625)

So how to obtain the `bev_feat_prev` during the current frame inference.
look forward your reply.

**Comment by LCH1238** [comment]
In this code, the model uses the BEV features of the previous 8 frames. However, if the current frame is in the initial stage, there are no previous 8 frames. For example, the current frame is the N th frame (N starts from 0),  if N <= 8,  the current bev features need to be copied 8 - N + 1 copies. If N > 8, there is no need to copy the current BEV feature.
